# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://uottahack.com"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "uOttaHack"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "uOttaHack: uOttawa's Inaugural Hackathon"
  description: "uOttaHack is a hackathon taking place at the University of Ottawa in February 2018. uOttaHack is the first MLH hackathon to take place at uOttawa.  Applications are now open, and student programmers of all skill levels are welcome to participate!  uOttaHack will be taking place over the weekend of February 17th and 18th, 2018."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "uOttaHack"
  description: "uOttawa's First MLH Hackathon."
  date:        "FEBRUARY 17 - 18 2018"
  location:    "UNIVERSITY OF OTTAWA"

  trust_badge:
    year:   "2018"  # season year
    region: "na"    # "na" or "eu"
    color:  "blue" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://uottahacks.github.io/landing-page/success.html"
      - text: "Say hi@uottahack.com"
        href: "mailto:hi@uottahack.com"

  about:
    description: >
      APPLICATIONS OPEN DECEMBER 4TH.
    mail: >
      Sign up below for updates and good news.

  # Frequently asked questions.
  faq:
    - question: "> What is uOttaHack?"
      answer: >
        uOttaHack is the first ever major [hackathon](https://www.youtube.com/watch?v=qj4DQfYx2Hg) hosted by University of Ottawa students! It's a weekend where students from all across Canada will come to turn their ideas into real projects, learn more than they could ever imagine, and have fun along the way!
    - question: "> Who can come?"
      answer: >
        Any student, at any skill level, from any field of study are welcome! The only thing you need is an interest in building something amazing, and the motivation to learn! <br /><br /> **Are you a recent grad?**  No worries - as long as you've graduated in the last 12 months, you're welcome to apply and attend!
    - question: "> Where and when is the event?"
      answer: >
        The hackathon will be hosted on the [beautiful campus of the University of Ottawa](https://goo.gl/qfoQx4), and will take place February 17th - 18th, 2018.
      # Embed a map to the venu here (or make it a section)
    - question: "> Can I work on a project I've already started?"
      answer: >
        All projects must be started from scratch at the event, but you're free to start thinking up an idea for one!
    - question: "> Can I participate as part of a group?"
      answer: >
        **Yes!**   Hacking can be done solo, or in a team of up to four participants.
    - question: "> How much will it cost me?"
      answer: >
        **Nothing at all!** Attending the hackathon is completely free, including any meals during the hackathon. We will also provide as much hype as you can possibly imagine.
    - question: "> What if I'm not from Ottawa?"
      answer: >
        We'd love to have you in the world's coldest capital! We'll be sending buses to areas where lots of hackers are coming from (Montreal, Waterloo, Toronto, etc.) as well as travel reimbursements. More info will be available closer to the hackathon!
    - question: "> Are newbie programmers and hackers allowed?"
      answer: >
        Of course! Hackathons are all about learning new things and having an amazing experience. We'll have plenty of workshops and mentors during the event to help you out!
    - question: "> Can high school students come?"
      answer: >
        **Yes!** We highly encourage younger high school students to apply and come get creative! Minors attending will be asked to have waivers signed by their parents/ guardians.
    - question: "> I think I'd rather help others learn instead of making my own hack - can I still come?"
      answer: >
        **Yes!** If you're experienced in CS and would like to be a student mentor, contact us at [hi@uottahack.com](mailto:plee032@uottawa.ca).
    - question: "> Sounds great, but what do I win?"
      answer: >
        We started uOttaHack to empower students in creating innovative, fun, and awesome projects, without the stress of a regular semester's weekend. The biggest reward you will get are the friends you make that last a lifetime, and an experience you won't forget. BUT with that said, you'll have the chance to demo to our stellar panel of judges and the top teams will be rewarded with some sweet prizes! There will also be smaller prizes for specific categories and potentially some given out by our sponors.
    - question: "> What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        They work with over 200 Member Events and empower over 70,000 students every year.
    - question: "> Is there a code of conduct?"
      answer: >
        Yes there is. The organizers care deeply about everyone's experience and ensuring they get to hack in a comfortable and safe environment. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "> 404 Question not found"
      answer: >
        Talk to us at [hi@uottahack.com](mailto:hi@uottahack.com)

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
